name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Ensure that only the latest commit is tested for PRs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: write # Needed for git-auto-commit-action

jobs:
  build_test_lint:
    name: "Build, Test, and Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        # Add cache-encryption-key if you set up the GRADLE_ENCRYPTION_KEY secret
        # with:
        #   cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug --no-configuration-cache

      - name: Commit Spotless changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 🤖 Apply Spotless formatting
          file_pattern: '**/*.kt **/*.kts **/*.java **/*.xml'


      - name: Run local unit tests
        run: ./gradlew testDebugUnitTest
        env:
            DEVELOCITY_ACCESS_KEY: ${{ secrets.DV_ACCESS_KEY }}

      - name: Verify Screenshot Tests (AndroidX)
        run: ./gradlew validateDebugScreenshotTest

      - name: Upload build outputs (APKs)
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: APKs
          path: '**/build/outputs/apk/debug/*.apk'

      - name: Upload JVM local test results (XML)
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: local-test-results
          path: '**/build/test-results/test*UnitTest/TEST-*.xml'

      - name: Upload lint reports (HTML)
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports-html
          path: '**/build/reports/lint-results-debug.html'

